support conditional DUDs

diff --git a/mkdud b/mkdud
--- a/mkdud
+++ b/mkdud
@@ -92,7 +92,7 @@ $Data::Dumper::Sortkeys = 1;
 $Data::Dumper::Terse = 1;
 $Data::Dumper::Indent = 1;
 
-our $VERSION = "1.3";
+our $VERSION = "1.4";
 
 my @all_archs = ( "x86_64", "i386", "ppc64", "ppc", "s390x", "s390", "ia64" );
 
@@ -109,6 +109,7 @@ sub fix_duds;
 sub show_dud;
 sub nice_arch_list;
 sub show_single_dir;
+sub get_service_pack;
 
 my $opt_create;
 my $opt_show;
@@ -122,6 +123,7 @@ my $opt_force;
 my $opt_save_temp;
 my %opt_install;
 my @opt_config;
+my @opt_condition;
 
 # global variables
 my $dud;
@@ -130,6 +132,16 @@ my @dists;
 my $dud_cnt = 0;
 my %arch;
 my $use_all_archs = 0;
+
+# linuxrc versions in service packs
+my $servicepack;
+$servicepack->{10}{1} = "2.0.67";
+$servicepack->{10}{2} = "2.0.79";
+$servicepack->{10}{3} = "2.0.91";
+$servicepack->{10}{4} = "2.0.97";
+$servicepack->{11}{1} = "3.3.59";
+$servicepack->{11}{2} = "3.3.81";
+$servicepack->{11}{3} = "3.3.91";
 
 GetOptions(
   'create|c=s'       => sub { $opt_create = 1; $dud = $_[1] },
@@ -141,6 +153,7 @@ GetOptions(
   'name|n=s'         => \@opt_name,
   'exec|x=s'         => \@opt_exec,
   'config=s'         => \@opt_config,
+  'condition=s'      => \@opt_condition,
   'may-replace-yast' => \$opt_force,
   'no-docs'          => \$opt_no_docs,
   'keep-docs'        => sub { $opt_no_docs = 0 },
@@ -276,8 +289,13 @@ Create driver update:
                                 Note that 'sle11' is a short hand for specifying both
                                 'sles11' and 'sled11'.
                                 Note also that there are no separate names for service packs.
-                                So 'sles11-sp1' is the same as 'sles11'.
+                                So 'sles11-sp1' is the same as 'sles11'. But see '--condition'
+                                below for a way to target specific service packs.
                                 Option can be repeated to specify several distribution targets.
+      --condition SCRIPT        Run SCRIPT and apply DUD only if SCRIPT has exit status 0.
+                                If SCRIPT has the special name ServicePackN (N = 1, 2, ...), a
+                                script that checks for service pack N is _generated_ and added.
+                                Option can be repeated to specify several conditions.
   -p, --prio NUM                Set repository priority to NUM (default: 50).
   -n, --name NAME               Set driver update name. If you update packages or modules
                                 a default name is generated based on the package and module
@@ -706,6 +724,13 @@ sub new_dud
     print $cfg "# created by mkdud $VERSION\n";
     print $cfg "UpdateID:\t$id\n";
 
+    for (@opt_condition) {
+      my $x = $_;
+      $x =~ s#.*/##;
+      next if $x eq "";
+      print $cfg "Exec:\t\t/update/*/install/mkdud.$id.if $x\n";
+    }
+
     my $has_update_name = @opt_name;
 
     # special case: allow otherwise empty update if a name was given explicitly
@@ -865,6 +890,75 @@ cd $dud/install
       close $x;
 
       chmod 0755, "$base/install/mkdud.$id.sh";
+    }
+
+    if(@opt_condition) {
+      $dud_ok = 1;
+      mkdir "$base/install", 0755;
+
+      my $c = <<'= = = = = = = =';
+#! /bin/bash
+
+# script generated by mkdud <version>
+
+# locate dud directory
+dud=${0%/install/*}
+
+[ -d "$dud" ] || exit 1
+
+export dud
+
+PATH=$dud/install:/bin:/sbin:/usr/bin:/usr/sbin
+
+cd $dud/install
+
+[ -x "./mkdud.$1" ] || exit 1
+
+"./mkdud.$1" || {
+  echo "The following Driver Update will *NOT* be applied:" >&2
+  echo "The following Driver Update will *NOT* be applied:"
+
+  rm -rf $dud/*
+
+  exit 1
+}
+
+exit 0
+= = = = = = = =
+
+      $c =~ s#<version>#$VERSION#;
+
+      open my $x, ">$base/install/mkdud.$id.if";
+      print $x $c;
+      close $x;
+
+      chmod 0755, "$base/install/mkdud.$id.if";
+
+      for (@opt_condition) {
+        if(/^ServicePack(\d+)$/) {
+          my $sp = get_service_pack $dist, $1;
+          if($sp) {
+            open my $x, ">$base/install/mkdud.$_";
+            print $x $sp;
+            close $x;
+            chmod 0755, "$base/install/mkdud.$_";
+          }
+          else {
+            die "error: no condition check for $dist $_\n";
+          }
+        }
+        elsif(-f) {
+          my $x = $_;
+          $x =~ s#.*/##;
+          if($x ne "") {
+            system "cp $_ $base/install/mkdud.$x";
+            chmod 0755, "$base/install/mkdud.$x";
+          }
+        }
+        else {
+          die "error: no such condition file: $_\n";
+        }
+      }
     }
 
     if(@rpms && $opt_install{repo}) {
@@ -1363,6 +1457,10 @@ sub show_single_dir
             }
           }
         }
+        elsif($val =~ m#/update/\*/install/(mkdud\..*\.if)\s+(\S+)$#) {
+          $ok = 1;
+          $sect{condition} .= "      $2\n";
+        }
         if(!$ok) {
           $sect{exec} .= "      $val\n";
         }
@@ -1550,6 +1648,10 @@ sub show_single_dir
 
   my $log;
 
+  if($sect{condition}) {
+    $log .= "    Conditions:\n$sect{condition}";
+  }
+
   if($sect{name}) {
     $log .= "    Name:\n$sect{name}";
   }
@@ -1593,4 +1695,38 @@ sub show_single_dir
   return $log;
 }
 
+
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+# $string = get_service_pack($dist, $sp)
+#
+# Return shell script that checks for service pack $sp on $dist.
+#
+sub get_service_pack
+{
+  my $dist = shift;
+  my $sp = shift;
+
+  my $linuxrc;
+
+  if($dist !~ /^sle.*?(\d+)$/ || ($linuxrc = $servicepack->{$1}{$sp}) eq "") {
+    return "";
+  }
+
+  my $c = <<'= = = = = = = =';
+#! /bin/bash
+
+# script generated by mkdud <version>
+
+while IFS="$IFS-" read pack ver xxx ; do
+  [ "$pack" = linuxrc -a "$ver" = <linuxrc> ] && exit 0
+done < /.packages.initrd
+
+exit 1
+= = = = = = = =
+
+  $c =~ s#<version>#$VERSION#;
+  $c =~ s#<linuxrc>#$linuxrc#;
+
+  return $c;
+}
 
